### ISSUE TITLE
Check fails when submodule path differs from submodule name

### ISSUE THREAD

**Issue by kopecs** [jtmullen/submodule-branch-check-action#23]
Currently the check at https://github.com/jtmullen/submodule-branch-check-action/blob/6c6f99f42640ce5247e478880be431940ad3c515/entrypoint.sh#L94-L95
and
https://github.com/jtmullen/submodule-branch-check-action/blob/6c6f99f42640ce5247e478880be431940ad3c515/entrypoint.sh#L119-L120
is incorrect---instead of checking if the path given to the action is the path of a submodule this checks if the path given is in the name of the _key_ corresponding to the path. This happens to work in the event that the submodule is named the same (which is a common case), but breaks when it is not.

For instance, this can be reproduces with a structure like the following:

```
repo-root
├── .gitmodules
├── main-repo-content
└── submodule-dir
   ├── .git
   └── submodule-content
```

where `.gitmodules` is as follows:

```ini
[submodule "submodule"]
	path = submodule-dir
	url = <arbitrary> 
```

which can be replicated by adding the submodule like so: `git submodule add --name submodule -- $URL submodule-dir`

Then a workflow like
```yaml
  check-submodules:
    name: check submodule branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check submodules
        uses: jtmullen/submodule-branch-check-action@v1
        with:
          path: submodule-dir
          branch: master
```
results in an error like
```
Error: path "submodule-dir" is not a submodule on $COMMIT
```
