### ISSUE TITLE
Action not work with tags on base repo

### ISSUE THREAD

**Issue by urbaned121** [jtmullen/submodule-branch-check-action#35]
Hi! In my scenario I want to trriger action with tags, so I'm doing:
git tag v0.0.6 
git push origin my-branch --tags  
then my workflow starts and throw error at:
```
Get Submodule Info
 Submodule path 'webapp': checked out '63ad3d11bb8......'
  Full Submodule History
  fatal: reference is not a tree: 0000000000000000000000000000000000000000
  Error: __Line:125__Error: Could not checkout 0000000000000000000000000000000000000000
```
  its probably caused by:
```
  Setup
  Run for push of refs/tags/v0.0.6 from 0000000000000000000000000000000000000000 to 7b98b541253e5dd3f79cfa...... on ORG/RepoName by urbaned121
```
  
  my workflow is: 
```
  name: Docker images

# Run this Build for all pushes to 'deployment-changes' or develop branch, or tagged releases.
# Also run for PRs to ensure PR doesn't break Docker build process
on:
  push:
    branches:
#      - my-branch
      - develop
    tags:
      - 'v**'
 
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          ref: my-branch

      - name: Checkout submodule repo
        uses: actions/checkout@v4
        with:
          repository: MySubRepo/webapp
          path: webapp
          token: ${{ secrets.PAT }}
      - name: Check Submodule Name
        uses: jtmullen/submodule-branch-check-action@v1.3.1
        with:
          path: webapp
          branch: deployment-changes
          first_parent: true
          fetch_depth: "1"
          pass_if_unchanged: true
          require_head: true
          disable_progression: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
        ..... 
 
```
 Action works well with pushes to my-branch but not work with tags
 Is there any solution or workaround? 
 Why I need it? 
 I need to use tags later in my action to tag my docker images
